include: package:very_good_analysis/analysis_options.2.0.1.yaml

analyzer:
  exclude:
    - '**.freezed.dart'
    - 'lib/resources/proto/**'
    - 'lib/resources/l10n/**'
    - 'lib/injection.config.dart'
    - "**/*.g.dart"
    - "**/*.mocks.dart"

linter:
  rules:
    unawaited_futures: false
    curly_braces_in_flow_control_structures: false
    library_prefixes: false
    public_member_api_docs: false
    omit_local_variable_types: false
    sort_constructors_first: false
    constant_identifier_names: false
    lines_longer_than_80_chars: false
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
